apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  tls:
    - hosts:
        - wouritech.com
        - api.wouritech.com
        - www.wouritech.com
      secretName: tls-secret
  defaultBackend:
    service:
      name: default-backend-svc
      port:
        number: 80
  rules:
    - host: wouritech.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: default-backend-svc
                port:
                  number: 80