apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: private-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
#    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - internal.wouritech.com
      secretName: internal-tls-secret
  rules:
    - host: internal.wouritech.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: internal-app-svc
                port: 
                  number: 80
