grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    labels: { }
    hosts:
      - grafana.wouritech.com
    path: /
    tls:
      - secretName: grafana-general-tls
        hosts:
         - grafana.wouritech.com

#  additionalDataSources:
#    - name: loki
#      type: loki
#      url: http://loki-loki-distributed-gateway.monitoring:80
#      access: proxy
#      isDefault: false
#  persistence:
#    enabled: true
#    type: pvc
#    storageClassName: do-block-storage
#    name: grafana-storage
#    size: 10Gi
#    accessModes:
#      - ReadWriteMany
#    finalizers:
#      - kubernetes.io/pvc-protection

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    labels: { }
    ## Redirect ingress to an additional defined port on the service
    # servicePort: 8081
    hosts:
      - prometheus.wouritech.com
    paths:
      - /

    ## For Kubernetes >= 1.18 you should specify the pathType (determines how Ingress paths should be matched)
    ## See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#better-path-matching-with-path-types
    # pathType: ImplementationSpecific

    tls:
      - secretName: prometheus-general-tls
        hosts:
         - prometheus.wouritech.com

#  prometheusSpec:
#    storageSpec:
#      volumeClaimTemplate:
#        spec:
#          name: prometheus-storage
#          storageClassName: "do-block-storage"
#          accessModes: ["ReadWriteMany"]
#          resources:
#            requests:
#              storage: "10Gi"

nodeExporter:
  enable: true
  operatingSystems:
    linux:
      enabled: true
    aix:
      enabled: false
    darwin:
      enabled: false
    windows:
      enabled: false

#alertmanager:
#  alertmanagerSpec:
#    storage:
#      volumeClaimTemplate:
#        spec:
#          storageClassName: "do-block-storage"
#          accessModes: ["ReadWriteOnce"]
#          name: alertmanager-storage
#          resources:
#            requests:
#              storage: "10Gi"
